# Generated by Django 5.1.4 on 2024-12-08 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=1, max_digits=10),
                ),
                ("max_products", models.IntegerField(default=10)),
                ("unlimited_products", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
