# Generated by Django 5.1.4 on 2024-12-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_subscriptionpayment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscriptionpayment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Complete", "Complete"),
                    ("Cancelled", "Cancelled"),
                    ("Future", "Future"),
                    ("Failed", "Failed"),
                    ("Incomplete", "Incomplete"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
