# Generated by Django 5.1.4 on 2024-12-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_subscriptionpayment_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="subscription",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscription",
            ),
        ),
    ]
