# Generated by Django 5.1.4 on 2024-12-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_alter_subscriptionpayment_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpayment",
            name="payment_link",
            field=models.URLField(null=True),
        ),
    ]
