# Generated by Django 5.1.4 on 2024-12-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_alter_business_owner"),
        ("payments", "0007_subscriptionpayment_payment_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="business_branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="businesses.businessbranch",
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="subscription_type",
            field=models.CharField(
                choices=[
                    ("Business Subscription", "Business Subscription"),
                    ("Branch Subscription", "Branch Subscription"),
                ],
                default="Business Subscription",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="business",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="businesses.business",
            ),
        ),
    ]
