# Generated by Django 5.1.4 on 2024-12-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0008_subscription_business_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpackage",
            name="currency",
            field=models.CharField(
                choices=[("KES", "KES"), ("USD", "USD")], default="KES", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="hosted_page",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="interval",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="plan_code",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="send_invoices",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subscriptionpackage",
            name="send_sms",
            field=models.BooleanField(default=True),
        ),
    ]
