# Generated by Django 5.1.4 on 2024-12-10 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_subscriptionpackage_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionpackage",
            name="subscription_page",
            field=models.UUIDField(null=True),
        ),
    ]
