# Generated by Django 5.1.4 on 2024-12-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_subscriptionpackage_subscription_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="subscription_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
