# Generated by Django 5.1.4 on 2024-12-09 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0002_alter_business_owner"),
        ("payments", "0008_subscription_business_branch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessbranch",
            name="subscription_package",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payments.subscriptionpackage",
            ),
        ),
    ]
