# Generated by Django 5.1.4 on 2024-12-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_businessbranch_subscription_package"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
