# Generated by Django 5.1.4 on 2024-12-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0005_business_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="paystack_customer_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
